# Generated by Django 5.2.7 on 2025-10-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_equipment_room"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["building", "capacity"], name="rooms_room_buildin_48b6a2_idx"
            ),
        ),
    ]
