# Generated by Django 5.2.7 on 2025-11-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_room_rooms_room_buildin_48b6a2_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="教室代碼"
                    ),
                ),
                ("building", models.CharField(max_length=50, verbose_name="大樓")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="教室名稱"
                    ),
                ),
                ("capacity", models.PositiveIntegerField(verbose_name="容納人數")),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "普通教室"),
                            ("LAB", "電腦教室"),
                            ("MEETING", "會議室"),
                            ("OTHER", "其他"),
                        ],
                        default="NORMAL",
                        max_length=20,
                        verbose_name="教室類型",
                    ),
                ),
                ("equipment", models.TextField(blank=True, verbose_name="設備說明")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="是否可借用"),
                ),
                ("note", models.TextField(blank=True, verbose_name="備註")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "教室",
                "verbose_name_plural": "教室",
            },
        ),
    ]
