# Generated by Django 5.2.7 on 2025-11-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_classroom"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classroom",
            options={"verbose_name": "教室", "verbose_name_plural": "教室列表"},
        ),
        migrations.AlterUniqueTogether(
            name="classroom",
            unique_together={("building", "room_code")},
        ),
        migrations.AddField(
            model_name="classroom",
            name="equipment_note",
            field=models.TextField(
                blank=True, verbose_name="設備備註（特殊設備、限制等）"
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="has_air_conditioner",
            field=models.BooleanField(default=True, verbose_name="冷氣"),
        ),
        migrations.AddField(
            model_name="classroom",
            name="has_fan",
            field=models.BooleanField(default=False, verbose_name="電風扇"),
        ),
        migrations.AddField(
            model_name="classroom",
            name="has_mic",
            field=models.BooleanField(default=False, verbose_name="麥克風"),
        ),
        migrations.AddField(
            model_name="classroom",
            name="has_projector",
            field=models.BooleanField(default=False, verbose_name="投影機"),
        ),
        migrations.AddField(
            model_name="classroom",
            name="has_screen",
            field=models.BooleanField(default=False, verbose_name="投影幕"),
        ),
        migrations.AddField(
            model_name="classroom",
            name="has_speaker",
            field=models.BooleanField(default=False, verbose_name="喇叭系統"),
        ),
        migrations.AddField(
            model_name="classroom",
            name="has_teacher_computer",
            field=models.BooleanField(default=False, verbose_name="教師電腦"),
        ),
        migrations.AddField(
            model_name="classroom",
            name="has_whiteboard",
            field=models.BooleanField(default=True, verbose_name="白板"),
        ),
        migrations.AddField(
            model_name="classroom",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否啟用"),
        ),
        migrations.AddField(
            model_name="classroom",
            name="power_socket_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="插座數量（估計即可）"
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="student_computer_count",
            field=models.PositiveIntegerField(default=0, verbose_name="學生電腦數量"),
        ),
        migrations.AddField(
            model_name="classroom",
            name="wheelchair_accessible",
            field=models.BooleanField(default=False, verbose_name="是否為無障礙教室"),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="building",
            field=models.CharField(
                choices=[
                    ("CS", "資訊館"),
                    ("E1", "第一教學大樓"),
                    ("E2", "第二教學大樓"),
                    ("M", "管理學院"),
                    ("S", "理學院"),
                ],
                max_length=10,
                verbose_name="大樓",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="name",
            field=models.CharField(blank=True, max_length=50, verbose_name="教室名稱"),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="room_code",
            field=models.CharField(max_length=20, verbose_name="教室代碼"),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("NORMAL", "普通教室"),
                    ("LAB", "電腦教室"),
                    ("MEETING", "會議室"),
                    ("LECTURE", "大講堂"),
                    ("OTHER", "其他"),
                ],
                default="NORMAL",
                max_length=20,
                verbose_name="教室類型",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="最後更新時間"),
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="is_available",
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="note",
        ),
    ]
