# Generated by Django 5.2.7 on 2025-11-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_alter_classroom_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="building",
        ),
        migrations.RemoveField(
            model_name="room",
            name="equipments",
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together=None,
        ),
        migrations.AlterField(
            model_name="classroom",
            name="building",
            field=models.CharField(
                choices=[
                    ("INS", "資工系館"),
                    ("ECG", "電資暨綜合教學大樓"),
                    ("LIB", "圖書館大樓"),
                    ("GH1", "綜合一館"),
                    ("GH2", "綜合二館"),
                ],
                max_length=10,
                verbose_name="大樓",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="room_code",
            field=models.CharField(max_length=20, unique=True, verbose_name="教室代碼"),
        ),
        migrations.DeleteModel(
            name="Building",
        ),
        migrations.DeleteModel(
            name="Equipment",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
