# Generated by Django 5.2.7 on 2025-12-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_room_building_remove_room_equipments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='has_network',
            field=models.BooleanField(default=True, verbose_name='網路'),
        ),
    ]
