# Generated by Django 5.2.7 on 2025-12-12 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
        ("rooms", "0007_classroom_has_network"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["classroom", "date", "time_slot", "status"],
                name="reservation_classro_93381f_idx",
            ),
        ),
    ]
